pipeline {
    agent any

    tools {
        maven 'Maven 3.8.1'
    }

    environment {
        SONARQUBE = 'SonarQube'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/iDL08/Project-test.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('simple-java-project') {
                    withSonarQubeEnv("${SONARQUBE}") {
                        sh 'ls -la' // Optional: to verify pom.xml is present
                        sh 'mvn clean verify sonar:sonar'
                    }
                }
            }
        }
    }
}

