pipeline {
    agent any

    tools {
        maven 'Maven 3.8.1'
    }

    environment {
        SONARQUBE = 'SonarQube'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/iDL08/Project-test.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('simple-java-project') {
                    withSonarQubeEnv("${SONARQUBE}") {
                        withCredentials([string(credentialsId: 'Sonartoken', variable: 'SONAR_TOKEN')]) {
                            sh 'mvn clean verify sonar:sonar -Dsonar.token=$SONAR_TOKEN'
                        }
                    }
                }
            }
        }
    }
}

